### PR TITLE
add flake8 test env to tox

### PR DESCRIPTION
**Pull request by cormier**

### CODE REVIEW

**Comment by swistakm** [comment]
Great! What are the results? Could you also add this env to Travis matrix?

**Comment by cormier** [comment]
Yes I added it to `tox.ini` and `.travis.yml`. I see that the environments are specified in both `.travis.yml` and `tox.ini`. Is it to see the details in the travis build job page? Otherwise I believe we could only specify them in `tox.ini` and run it without the `-e` argument.

**Comment by swistakm** [comment]
Yes this is mostly in order to split different environments into separate travis build matrix entries. I know this seems a bit redundant, and requires extra maintenance. I don't like it too.

Anyway, it really helps in resolving issues found in CI because it is instantly clear on which environment build failed.

**Comment by cormier** [comment]
That makes sense. And since we don't modify these files often I think it's worth it. Thanks!

**Pull request merged**
